CREATE TABLE IF NOT EXISTS EQUIPAMENTO(
	COD_EQUIPAMENTO SERIAL,
	NM_EQUIPAMENTO VARCHAR(100) NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL,
	QUANTIDADE INT NOT NULL,
	TIPO VARCHAR (60) NOT NULL,
	--CHAVE PRIMARIA
	CONSTRAINT EQUIPAMENTO_PK PRIMARY KEY(COD_EQUIPAMENTO)
);

CREATE TABLE IF NOT EXISTS CURSO(
	COD_CURSO SERIAL,
	NOME_CURSO VARCHAR(60) NOT NULL,
	--CHAVE PRIMARIA
	CONSTRAINT CURSO_PK PRIMARY KEY(COD_CURSO)
);

CREATE TABLE IF NOT EXISTS SALA(
	COD_SALA SERIAL,
	NOME_SALA VARCHAR(60) NOT NULL,
	--CHAVE PRIMARIA
	CONSTRAINT SALA_PK PRIMARY KEY(COD_SALA)
);

CREATE TABLE IF NOT EXISTS PROFESSOR(
	COD_PROFESSOR SERIAL,
	NM_PROFESSOR VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	COD_CURSO INT,
	SALARIO DECIMAL(10, 2) NOT NULL,
	--CHAVE PRIMARIA
	CONSTRAINT PROFESSOR_COD_PROFESSOR_PK PRIMARY KEY(COD_PROFESSOR),
	--CHAVE ESTRANGEIRA
	CONSTRAINT PROFESSOR_COD_CURSO_FK FOREIGN KEY(COD_CURSO)
	REFERENCES CURSO(COD_CURSO)
);

CREATE TABLE IF NOT EXISTS RESERVA(
	COD_EQUIPAMENTO INT,
	COD_PROFESSOR INT,
	DT_RESERVAR DATE,
	HORARIO VARCHAR(10),
	COD_SALA INT,
	--CHAVE PRIMARIA
	CONSTRAINT RSVA_EQUIP_PROF_SALA_PK PRIMARY KEY(COD_EQUIPAMENTO, COD_PROFESSOR, COD_SALA),
	--CHAVE ESTRANGEIRA
	CONSTRAINT RSVA_EQUIPAMENTO_FK FOREIGN KEY(COD_EQUIPAMENTO)
	REFERENCES EQUIPAMENTO(COD_EQUIPAMENTO),
	CONSTRAINT RSVA_PROFESSOR_FK FOREIGN KEY(COD_PROFESSOR)
	REFERENCES PROFESSOR(COD_PROFESSOR),
	CONSTRAINT RSVA_SALA_FK FOREIGN KEY(COD_SALA)
	REFERENCES SALA(COD_SALA)
);
