-- SELECT TABLE_SCHEMA, TABLE_NAME FROM
-- INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA NOT IN
-- ('information_schema', 'pg_catalog') AND table_type = 'BASE TABLE'
-- ORDER BY  TABLE_NAME, TABLE_SCHEMA

-- ESQUEMA RELACIONAL EXEMPLO
-- EMPREGADO (MATRICULA, NOME_EMPREGADO, SALARIO, NUM_DEPTO)

-- DEPARTAMENTO (NUM_DEPTO, NOME_DEPTO)

CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
	NUM_DEPTO SERIAL NOT NULL,
	NOME_DEPTO VARCHAR(60) NOT NULL,
	--CHAVE PRIMÁRIA
	CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY(NUM_DEPTO)
);

ALTER SEQUENCE departamento_num_depto_seq RESTART WITH 1000;

-- CADASTRANDO DEPARTAMENTOS (SELECT * FROM DEPARTAMENTO)
INSERT INTO DEPARTAMENTO (NOME_DEPTO) VALUES 
('RH'),
('MARKETING'),
('VENDAS'),
('DEVs')


SELECT column_name, data_type, character_maximum_length, is_nullable
FROM information_schema.columns
WHERE table_name = 'DEPARTAMENTO'
ORDER BY ordinal_position;

SELECT 
    c.table_schema,
    c.table_name,
    c.column_name,
    c.data_type,
    c.column_default LIKE 'nextval%' AS is_serial
FROM 
    information_schema.columns c
WHERE 
    c.table_name = 'DEPARTAMENTO'
ORDER BY 
    c.ordinal_position;


SELECT * FROM DEPARTAMENTO;


-- PROJETO (NUM_PROJ, NOME_PROJETO, LUGAR)
-- TRABALHA (MAT_EMPREGADO, NUM_PROJ, HORAS)
-- DEPENDENTE (MATRICULA_EMPREG, NOME_DEPENDENTE, GRAU_PARENTESCO)


-- CREATE TABLE IF NOT EXISTS SETORES(
--     NUM_DEPTO UUID DEFAULT gen_random_uuid() NOT NULL,
--     NOME_DEPTO VARCHAR(60) NOT NULL,
--     CONSTRAINT SETORES_PK PRIMARY KEY(NUM_DEPTO)
-- );

-- INSERT INTO SETORES (NOME_DEPTO) VALUES 
-- ('RH'),
-- ('MARKETING'),
-- ('VENDAS'),
-- ('DEVs')

-- DROP TABLE SETORES;
