--SELECT * FROM DEPARTAMENTO
CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
	NUM_DEPTO SERIAL,
	NOME_DEPTO VARCHAR(60) NOT NULL,
	--CHAVE PRIMARIA
	CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY(NUM_DEPTO)
);

--SELECT * FROM EMPREGADO
CREATE TABLE IF NOT EXISTS EMPREGADO(
	MATRICULA SERIAL,
	NOME_EMPREGADO VARCHAR(50) NOT NULL,
	SALARIO DECIMAL(10,2),
	NUM_DEPTO INT,
	--CHAVE PRIMARIA
	CONSTRAINT EMPREGADO_PK PRIMARY KEY (MATRICULA),
	--CHAVE ESTRANGEIRA
	CONSTRAINT EMPREG_DEPTO_FK FOREIGN KEY (NUM_DEPTO)
	REFERENCES DEPARTAMENTO(NUM_DEPTO)
);